status = [
    "rustfmt",
    "lint",
    "build (ubuntu-latest)",
    "build (windows-latest)",
    "build (macos-latest)",
    "test (ubuntu-latest)",
    "test (windows-latest)",
    "test (macos-latest)",
]
